#pragma once

constexpr float VELOCITY_SELF_DESTRUCTION_THRESHOLD = 0.05f;
constexpr float VELOCITY_BREAK_BRICK_THRESHOLD = 2.0f;

constexpr float BRICK_FRICTION_COEFFICIENT = 1.2f;
constexpr float BRICK_STICTION_THRESHOLD = 0.001f;

constexpr float PROJECTILE_FRICTION_COEFFICIENT = 1.2f;
constexpr float PROJECTILE_STICTION_THRESHOLD = 0.001f;
